### ISSUE TITLE
Minor documentation notes

### ISSUE THREAD

**Issue by bdferris642** [ajaynadig/TRADE#1]
Thank you for building this useful package and for all the helpful documentation! You might want to add that `ashr` is a required package. Also, the link to the manuscript in the main page appears to just read `PAPER LINK` :)

**Comment by ajaynadig** [comment]
Thanks for the heads up, I just added package dependencies to the DESCRIPTION and NAMESPACE files, and installing the package should now appropriately install ashr and other dependencies.

The paper does not yet publicly exist but will hopefully be uploaded to bioRxiv in the coming week!

**Comment by ajaynadig** [comment]
Added paper link, closing now
