### ISSUE TITLE
Arguments not passed to inner TRADE_bivariate call

### ISSUE THREAD

**Issue by deto** [ajaynadig/TRADE#4]
https://github.com/ajaynadig/TRADE/blob/36db75b62bdcd36300bece1784ee375e292aaa8b/R/TRADE.R#L83-L90

Here it looks like the arguments that are used in the `TRADE` method are not passed to the `TRADE_bivariate` call.

**Comment by ajaynadig** [comment]
Just fixed this, thank you for pointing out, and apologies for the delay!

**Comment by ajaynadig** [comment]
Closing now, feel free to reopen if problem persists
