### ISSUE TITLE
error in evaluating the argument 'x' in selecting a method for function 'colSums': missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by deto** [ajaynadig/TRADE#5]
https://github.com/ajaynadig/TRADE/blob/36db75b62bdcd36300bece1784ee375e292aaa8b/R/TRADE_bivariate.R#L73-L76

Ran into the above error when running the bivariate comparison.  Traced it to this line - it appears to happen when there are NAs in the logfc or the SE vector.  Suggest adding some automatic filtering or a warning for future users.

**Comment by ajaynadig** [comment]
Added a "stop" command to check for NAs, thank you for pointing out this and other bugs, it is very helpful!

**Comment by ajaynadig** [comment]
Closing now, feel free to reopen if problem persists
